# Generated by Django 5.2.1 on 2025-05-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_task_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
