# Generated by Django 5.2.1 on 2025-05-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
