# Generated by Django 5.2.1 on 2025-06-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline']},
        ),
    ]
