# Generated by Django 5.2.1 on 2025-06-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Ongoing', 'Ongoing'), ('Not Starter', 'Not Started')], default='Not Started', max_length=15),
        ),
    ]
