# Generated by Django 5.2.1 on 2025-06-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Ongoing', 'Ongoing'), ('Not Started', 'Not Started')], default='Not Started', max_length=15),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
